# Generated by Django 4.1.7 on 2023-10-09 12:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='qualification',
            name='degree',
        ),
    ]
