# Generated by Django 4.1.7 on 2023-10-10 04:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0003_user_email'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='qualification',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='student.qualification'),
        ),
    ]
