# Generated by Django 4.1.7 on 2023-10-10 04:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0004_alter_user_qualification'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='date_of_birth',
            field=models.DateField(blank=True, choices=[('1', 'female'), ('2', 'male')], null=True),
        ),
    ]
