# Generated by Django 4.1.7 on 2023-10-10 04:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0006_alter_user_date_of_birth_alter_user_gender'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='gender',
            field=models.CharField(blank=True, choices=[('1', 'female'), ('2', 'male'), ('3', 'other')], max_length=10, null=True),
        ),
    ]
