# Generated by Django 4.1.7 on 2023-10-10 10:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0009_alter_address_city_alter_address_country_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='user_type',
            field=models.CharField(blank=True, choices=[('1', 'Student'), ('2', 'Teacher')], max_length=20, null=True, verbose_name='user type'),
        ),
    ]
