# Generated by Django 4.1.7 on 2023-10-10 10:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0010_alter_user_user_type'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='phone_number',
        ),
    ]
