# Generated by Django 4.1.7 on 2023-10-12 09:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0012_remove_user_qualification_delete_qualification'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='admission_date',
        ),
        migrations.RemoveField(
            model_name='user',
            name='current_class',
        ),
        migrations.RemoveField(
            model_name='user',
            name='roll_number',
        ),
    ]
