# Generated by Django 4.1.7 on 2023-10-18 06:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0020_alter_user_user_type'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='roll_number',
        ),
    ]
