# Generated by Django 4.1.7 on 2023-10-19 09:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0022_user_is_active'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='email',
            field=models.EmailField(blank=True, max_length=254, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='is_active',
            field=models.BooleanField(blank=True, default=True, null=True),
        ),
    ]
