# Generated by Django 4.1.7 on 2023-10-12 05:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('student', '0011_remove_user_phone_number'),
    ]

    operations = [
        migrations.CreateModel(
            name='Teacher',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('highest_qualification', models.CharField(blank=True, choices=[('1', 'Diploma'), ('2', 'UG'), ('3', 'PG')], max_length=20, null=True)),
                ('institution', models.CharField(blank=True, max_length=100, null=True)),
                ('field_of_study', models.CharField(blank=True, max_length=100, null=True)),
                ('passoutyear', models.DateField(blank=True, null=True)),
                ('subject_taught', models.CharField(blank=True, max_length=100, null=True)),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='student.user')),
            ],
        ),
    ]
