# Generated by Django 4.1.7 on 2023-10-12 05:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('teacherapp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Qualification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('highest_qualification', models.CharField(blank=True, choices=[('1', 'Diploma'), ('2', 'UG'), ('3', 'PG')], max_length=20, null=True)),
                ('institution', models.CharField(blank=True, max_length=100, null=True)),
                ('field_of_study', models.CharField(blank=True, max_length=100, null=True)),
                ('passoutyear', models.DateField(blank=True, null=True)),
            ],
        ),
        migrations.RemoveField(
            model_name='teacher',
            name='field_of_study',
        ),
        migrations.RemoveField(
            model_name='teacher',
            name='highest_qualification',
        ),
        migrations.RemoveField(
            model_name='teacher',
            name='institution',
        ),
        migrations.RemoveField(
            model_name='teacher',
            name='passoutyear',
        ),
        migrations.AddField(
            model_name='teacher',
            name='qualification',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='teacherapp.qualification'),
        ),
    ]
