# Generated by Django 4.1.7 on 2023-10-12 06:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('teacherapp', '0002_qualification_remove_teacher_field_of_study_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='teacher',
            name='subject_taught',
        ),
        migrations.AddField(
            model_name='teacher',
            name='experience_in_years',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
