# Generated by Django 4.1.7 on 2023-10-19 04:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('teacherapp', '0003_remove_teacher_subject_taught_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='teacher',
            name='is_active',
            field=models.BooleanField(blank=True, null=True),
        ),
    ]
