# Generated by Django 4.1.7 on 2023-10-19 04:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('teacherapp', '0004_teacher_is_active'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='teacher',
            name='is_active',
        ),
    ]
