# Generated by Django 4.1.7 on 2023-10-12 05:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('studentapp', '0002_student_blood_group'),
    ]

    operations = [
        migrations.RenameField(
            model_name='student',
            old_name='current_class',
            new_name='division',
        ),
    ]
