# Generated by Django 4.1.7 on 2023-10-12 05:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('studentapp', '0003_rename_current_class_student_division'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='student',
            name='instructor_name',
        ),
    ]
