# Generated by Django 4.1.7 on 2023-10-12 06:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('studentapp', '0004_remove_student_instructor_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='caste',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
