# Generated by Django 4.1.7 on 2023-10-15 15:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('studentapp', '0006_alter_student_roll_number_alter_student_user'),
    ]

    operations = [
        migrations.RenameField(
            model_name='student',
            old_name='addmission_date',
            new_name='admission_date',
        ),
        migrations.AlterField(
            model_name='student',
            name='roll_number',
            field=models.CharField(blank=True, max_length=20, null=True, unique=True),
        ),
    ]
