# Generated by Django 4.1.7 on 2023-10-15 15:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('studentapp', '0007_rename_addmission_date_student_admission_date_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='student',
            old_name='admission_date',
            new_name='addmission_date',
        ),
    ]
