# Generated by Django 4.1.7 on 2023-10-18 06:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('studentapp', '0010_alter_student_roll_number'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='is_active',
            field=models.BooleanField(blank=True, null=True),
        ),
    ]
