# Generated by Django 4.1.7 on 2023-10-20 07:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('studentapp', '0012_remove_student_is_active'),
    ]

    operations = [
        migrations.CreateModel(
            name='MarkList',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('exam_date', models.DateField(blank=True, null=True)),
                ('exam_name', models.CharField(blank=True, max_length=120, null=True)),
                ('marks_obtained', models.PositiveIntegerField(blank=True, null=True)),
                ('subject_name', models.CharField(blank=True, max_length=120, null=True)),
                ('student_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='studentapp.student')),
            ],
        ),
    ]
